# Generated by Django 3.0.8 on 2020-08-27 04:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('htmlcube', '0003_auto_20200827_0448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzle',
            name='history',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puzzle', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='snap',
            field=models.TextField(),
        ),
    ]
