# Generated by Django 3.0.8 on 2020-08-27 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htmlcube', '0005_auto_20200827_0452'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='lastSave',
            field=models.CharField(default='', max_length=50),
        ),
    ]
