# Generated by Django 3.0.8 on 2020-08-27 22:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('htmlcube', '0006_puzzle_lastsave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzle',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
